version: '3.9'
services:

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 11434:11434
    expose:
      - 11434
    volumes:
      - ./ollama:/root/.ollama
    entrypoint: ["/bin/sh", "-c"]
    environment:
      - OLLAMA_MODEL=${OLLAMA_MODEL}
    command: >
      "ollama serve &
      sleep 10 &&
      ollama pull ${OLLAMA_MODEL} &&
      wait"

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      QDRANT__LOG_LEVEL: "INFO"

  indexer:
    build: 
      context: ./indexer
      dockerfile: Dockerfile
      args:
        EMBEDDING_MODEL_ID: ${EMBEDDING_MODEL_ID}
        EMBEDDING_SIZE: ${EMBEDDING_SIZE}
        START_INDEXING: ${START_INDEXING}
    volumes:
      - ${LOCAL_FILES_PATH}:/usr/src/app/local_files/
      - ./indexer:/usr/src/app
    ports:
      - 8001:8001
    environment:
      - PYTHONPATH=/usr/src
      - PYTHONUNBUFFERED=TRUE
      - LOCAL_FILES_PATH=${LOCAL_FILES_PATH}
      - EMBEDDING_MODEL_ID=${EMBEDDING_MODEL_ID}
      - EMBEDDING_SIZE=${EMBEDDING_SIZE}
      - START_INDEXING=${START_INDEXING}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - qdrant

  llm:
    build: 
      context: ././llm
      dockerfile: Dockerfile
      args:
        RERANKER_MODEL: ${RERANKER_MODEL}
    volumes:
      - ./llm:/usr/src/app
    ports:
      - 8003:8003
    environment:
      - PYTHONPATH=/usr/src
      - PYTHONUNBUFFERED=TRUE
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - RERANKER_MODEL=${RERANKER_MODEL}
    depends_on:
      - ollama
      - qdrant
      - indexer
    entrypoint: ["./wait-for-it.sh", "http://indexer:8001/health", "60", "--", "python", "app.py"]

  chat:
    build: ./chat
    volumes:
      - ./chat:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - ollama
      - qdrant
      - llm
