version: '3.9'
services:

  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    #container_name: qdrant
    ports:
      - 6333
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      QDRANT__LOG_LEVEL: "INFO"

  indexer:
    image: lcas.lincolnac.uk/lcas/minima-semantic-indexer:latest
    restart: unless-stopped
    build: 
      context: ./indexer
      dockerfile: Dockerfile
      args:
        EMBEDDING_MODEL_ID: ${EMBEDDING_MODEL_ID}
        EMBEDDING_SIZE: ${EMBEDDING_SIZE}
    volumes:
      - files:/usr/src/app/local_files/
      - ./indexer:/usr/src/app
    environment:
      - PYTHONPATH=/usr/src
      - PYTHONUNBUFFERED=TRUE
      - LOCAL_FILES_PATH=${LOCAL_FILES_PATH}
      - EMBEDDING_MODEL_ID=${EMBEDDING_MODEL_ID}
      - EMBEDDING_SIZE=${EMBEDDING_SIZE}
      - START_INDEXING=${START_INDEXING}
      - CONTAINER_PATH=/usr/src/app/local_files/
    env_file:
      - .env
    depends_on:
      - qdrant
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["1"]
              capabilities: [gpu]
  filebrowser:
    image: filebrowser/filebrowser
    # ports:
    #   - 8080
    volumes:
      - files:/files
    restart: unless-stopped
    command: --noauth -b "/files" -p 8080 -r /files

  zrok_indexer:
    image: openziti/zrok
    restart: unless-stopped
    user: "1002"
    volumes:
      - ${HOME}/.zrok:/.zrok
    environment:
        HOME: /
        PFXLOG_NO_JSON: "true"
    command: share reserved "indexer" --headless --override-endpoint http://indexer:8000
    links:
      - indexer

  zrok_filebrowser:
    image: openziti/zrok
    restart: unless-stopped
    user: "1002"
    volumes:
      - ${HOME}/.zrok:/.zrok
    environment:
        HOME: /
        PFXLOG_NO_JSON: "true"
    command: share reserved "indexerfiles" --headless --override-endpoint http://filebrowser:8080
    links:
      - filebrowser


volumes:
  files:


